# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1436, 873)
        MainWindow.setStyleSheet("QStatusBar{\n"
"  font-family: \"Josefin Sans Medium\",Arial,sans-serif;\n"
"  font-size: 14px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("/* CSS */\n"
"QGroupBox {\n"
"  font-family: \"Josefin Sans Medium\",Arial,sans-serif;\n"
"  font-size: 14px;\n"
"}\n"
"\n"
"#centralwidget {\n"
"    background-color:#fff;\n"
"}\n"
"\n"
"QLabel {\n"
"  font-family: \"Josefin Sans Medium\",Arial,sans-serif;\n"
"  font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"  background-image: linear-gradient(#f7f8fa ,#e7e9ec);\n"
"  border-color: #adb1b8 #a2a6ac #8d9096;\n"
"  border-style: solid;\n"
"  border-width: 1px;\n"
"  border-radius: 3px;\n"
"  box-shadow: rgba(255,255,255,.6) 0 1px 0 inset;\n"
"  box-sizing: border-box;\n"
"  color: #0f1111;\n"
"  cursor: pointer;\n"
"  display: inline-block;\n"
"  font-family: \"Josefin Sans Medium\",Arial,sans-serif;\n"
"  font-size: 14px;\n"
"  height: 29px;\n"
"  font-size: 13px;\n"
"  outline: 0;\n"
"  overflow: hidden;\n"
"  padding: 0 11px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  text-overflow: ellipsis;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  white-space: nowrap;\n"
"}\n"
"\n"
"QPushButton:active {\n"
"  border-bottom-color: #a2a6ac;\n"
"}\n"
"\n"
"QPushButton:active:hover {\n"
"  border-bottom-color: #a2a6ac;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  border-color: #a2a6ac #979aa1 #82858a;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"  border-color: #00a8ff;\n"
"  box-shadow: rgba(228, 121, 17, .5) 0 0 3px 2px;\n"
"  outline: 0;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 1181, 821))
        self.graphicsView.setObjectName("graphicsView")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(1210, 90, 211, 621))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.log_transform_button = QtWidgets.QPushButton(self.page)
        self.log_transform_button.setObjectName("log_transform_button")
        self.verticalLayout.addWidget(self.log_transform_button)
        self.gamma_transform_button = QtWidgets.QPushButton(self.page)
        self.gamma_transform_button.setObjectName("gamma_transform_button")
        self.verticalLayout.addWidget(self.gamma_transform_button)
        self.invert_image_button = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.invert_image_button.sizePolicy().hasHeightForWidth())
        self.invert_image_button.setSizePolicy(sizePolicy)
        self.invert_image_button.setObjectName("invert_image_button")
        self.verticalLayout.addWidget(self.invert_image_button)
        self.histogram_equal_button = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.histogram_equal_button.sizePolicy().hasHeightForWidth())
        self.histogram_equal_button.setSizePolicy(sizePolicy)
        self.histogram_equal_button.setMaximumSize(QtCore.QSize(16777215, 23))
        self.histogram_equal_button.setObjectName("histogram_equal_button")
        self.verticalLayout.addWidget(self.histogram_equal_button)
        self.view_histogram_button = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.view_histogram_button.sizePolicy().hasHeightForWidth())
        self.view_histogram_button.setSizePolicy(sizePolicy)
        self.view_histogram_button.setObjectName("view_histogram_button")
        self.verticalLayout.addWidget(self.view_histogram_button)
        self.find_edge_button = QtWidgets.QPushButton(self.page)
        self.find_edge_button.setObjectName("find_edge_button")
        self.verticalLayout.addWidget(self.find_edge_button)
        self.line = QtWidgets.QFrame(self.page)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.blur_label = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blur_label.sizePolicy().hasHeightForWidth())
        self.blur_label.setSizePolicy(sizePolicy)
        self.blur_label.setObjectName("blur_label")
        self.verticalLayout.addWidget(self.blur_label)
        self.blur_slider = QtWidgets.QSlider(self.page)
        self.blur_slider.setMaximum(20)
        self.blur_slider.setPageStep(1)
        self.blur_slider.setOrientation(QtCore.Qt.Horizontal)
        self.blur_slider.setObjectName("blur_slider")
        self.verticalLayout.addWidget(self.blur_slider)
        self.contrast_label = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contrast_label.sizePolicy().hasHeightForWidth())
        self.contrast_label.setSizePolicy(sizePolicy)
        self.contrast_label.setObjectName("contrast_label")
        self.verticalLayout.addWidget(self.contrast_label)
        self.contrast_slider = QtWidgets.QSlider(self.page)
        self.contrast_slider.setMaximum(20)
        self.contrast_slider.setPageStep(1)
        self.contrast_slider.setProperty("value", 10)
        self.contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.contrast_slider.setObjectName("contrast_slider")
        self.verticalLayout.addWidget(self.contrast_slider)
        self.sharpen_label = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sharpen_label.sizePolicy().hasHeightForWidth())
        self.sharpen_label.setSizePolicy(sizePolicy)
        self.sharpen_label.setObjectName("sharpen_label")
        self.verticalLayout.addWidget(self.sharpen_label)
        self.sharpen_slider = QtWidgets.QSlider(self.page)
        self.sharpen_slider.setMinimum(0)
        self.sharpen_slider.setMaximum(20)
        self.sharpen_slider.setPageStep(1)
        self.sharpen_slider.setTracking(True)
        self.sharpen_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sharpen_slider.setObjectName("sharpen_slider")
        self.verticalLayout.addWidget(self.sharpen_slider)
        self.color_label = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_label.sizePolicy().hasHeightForWidth())
        self.color_label.setSizePolicy(sizePolicy)
        self.color_label.setObjectName("color_label")
        self.verticalLayout.addWidget(self.color_label)
        self.color_slider = QtWidgets.QSlider(self.page)
        self.color_slider.setMaximum(20)
        self.color_slider.setPageStep(1)
        self.color_slider.setProperty("value", 10)
        self.color_slider.setOrientation(QtCore.Qt.Horizontal)
        self.color_slider.setObjectName("color_slider")
        self.verticalLayout.addWidget(self.color_slider)
        self.bright_label = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bright_label.sizePolicy().hasHeightForWidth())
        self.bright_label.setSizePolicy(sizePolicy)
        self.bright_label.setObjectName("bright_label")
        self.verticalLayout.addWidget(self.bright_label)
        self.bright_slider = QtWidgets.QSlider(self.page)
        self.bright_slider.setMaximum(20)
        self.bright_slider.setPageStep(1)
        self.bright_slider.setProperty("value", 10)
        self.bright_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bright_slider.setObjectName("bright_slider")
        self.verticalLayout.addWidget(self.bright_slider)
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.page_3)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pink_dream_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.pink_dream_filter_button.setObjectName("pink_dream_filter_button")
        self.verticalLayout_6.addWidget(self.pink_dream_filter_button)
        self.cyperpunk_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.cyperpunk_filter_button.setObjectName("cyperpunk_filter_button")
        self.verticalLayout_6.addWidget(self.cyperpunk_filter_button)
        self.snowy_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.snowy_filter_button.setObjectName("snowy_filter_button")
        self.verticalLayout_6.addWidget(self.snowy_filter_button)
        self.pastel_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.pastel_filter_button.setObjectName("pastel_filter_button")
        self.verticalLayout_6.addWidget(self.pastel_filter_button)
        self.firestorm_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.firestorm_filter_button.setObjectName("firestorm_filter_button")
        self.verticalLayout_6.addWidget(self.firestorm_filter_button)
        self.ice_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.ice_filter_button.setObjectName("ice_filter_button")
        self.verticalLayout_6.addWidget(self.ice_filter_button)
        self.darkness_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.darkness_filter_button.setObjectName("darkness_filter_button")
        self.verticalLayout_6.addWidget(self.darkness_filter_button)
        self.gray_nostalgia_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.gray_nostalgia_filter_button.setObjectName("gray_nostalgia_filter_button")
        self.verticalLayout_6.addWidget(self.gray_nostalgia_filter_button)
        self.sweet_dream_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.sweet_dream_filter_button.setObjectName("sweet_dream_filter_button")
        self.verticalLayout_6.addWidget(self.sweet_dream_filter_button)
        self.cartoon_filter_button = QtWidgets.QPushButton(self.groupBox)
        self.cartoon_filter_button.setObjectName("cartoon_filter_button")
        self.verticalLayout_6.addWidget(self.cartoon_filter_button)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.flip_group_box = QtWidgets.QGroupBox(self.page_2)
        self.flip_group_box.setObjectName("flip_group_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.flip_group_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.flip_updown_button = QtWidgets.QPushButton(self.flip_group_box)
        self.flip_updown_button.setObjectName("flip_updown_button")
        self.verticalLayout_3.addWidget(self.flip_updown_button)
        self.flip_leftright_button = QtWidgets.QPushButton(self.flip_group_box)
        self.flip_leftright_button.setObjectName("flip_leftright_button")
        self.verticalLayout_3.addWidget(self.flip_leftright_button)
        self.verticalLayout_2.addWidget(self.flip_group_box)
        self.rotate_group_box = QtWidgets.QGroupBox(self.page_2)
        self.rotate_group_box.setObjectName("rotate_group_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.rotate_group_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rotate_left_button = QtWidgets.QPushButton(self.rotate_group_box)
        self.rotate_left_button.setObjectName("rotate_left_button")
        self.verticalLayout_4.addWidget(self.rotate_left_button)
        self.rotate_right_button = QtWidgets.QPushButton(self.rotate_group_box)
        self.rotate_right_button.setObjectName("rotate_right_button")
        self.verticalLayout_4.addWidget(self.rotate_right_button)
        self.verticalLayout_2.addWidget(self.rotate_group_box)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1210, 10, 211, 63))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.open_button.setObjectName("open_button")
        self.horizontalLayout.addWidget(self.open_button)
        self.save_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(1210, 710, 211, 63))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prev_page_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.prev_page_button.setObjectName("prev_page_button")
        self.horizontalLayout_2.addWidget(self.prev_page_button)
        self.next_page_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.next_page_button.setObjectName("next_page_button")
        self.horizontalLayout_2.addWidget(self.next_page_button)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(1210, 780, 211, 63))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.undo_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.undo_button.setObjectName("undo_button")
        self.horizontalLayout_3.addWidget(self.undo_button)
        self.original_image_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.original_image_button.setObjectName("original_image_button")
        self.horizontalLayout_3.addWidget(self.original_image_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1436, 25))
        self.menubar.setStyleSheet("QMenuBar {\n"
"  font-family: \"Josefin Sans Medium\",Arial,sans-serif;\n"
"  font-size: 12px;\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_us = QtWidgets.QAction(MainWindow)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.menuExit.addAction(self.actionAbout_us)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.log_transform_button.setText(_translate("MainWindow", "Log Transform"))
        self.gamma_transform_button.setText(_translate("MainWindow", "Gamma Transform"))
        self.invert_image_button.setText(_translate("MainWindow", "Invert Image"))
        self.histogram_equal_button.setText(_translate("MainWindow", "Histogram Equalization"))
        self.view_histogram_button.setText(_translate("MainWindow", "View Histogram"))
        self.find_edge_button.setText(_translate("MainWindow", "Find Edge"))
        self.blur_label.setText(_translate("MainWindow", "Blur"))
        self.contrast_label.setText(_translate("MainWindow", "Contrast"))
        self.sharpen_label.setText(_translate("MainWindow", "Sharpen"))
        self.color_label.setText(_translate("MainWindow", "Color"))
        self.bright_label.setText(_translate("MainWindow", "Brightness"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter List"))
        self.pink_dream_filter_button.setText(_translate("MainWindow", "Pink Dream"))
        self.cyperpunk_filter_button.setText(_translate("MainWindow", "Cyperpunk 2077"))
        self.snowy_filter_button.setText(_translate("MainWindow", "Snowy"))
        self.pastel_filter_button.setText(_translate("MainWindow", "Pastel"))
        self.firestorm_filter_button.setText(_translate("MainWindow", "Firestorm"))
        self.ice_filter_button.setText(_translate("MainWindow", "Ice"))
        self.darkness_filter_button.setText(_translate("MainWindow", "Darkness"))
        self.gray_nostalgia_filter_button.setText(_translate("MainWindow", "Gray Nostalgia"))
        self.sweet_dream_filter_button.setText(_translate("MainWindow", "Sweet Dream"))
        self.cartoon_filter_button.setText(_translate("MainWindow", "Cartoon"))
        self.flip_group_box.setTitle(_translate("MainWindow", "Flip Image"))
        self.flip_updown_button.setText(_translate("MainWindow", "Up - Down"))
        self.flip_leftright_button.setText(_translate("MainWindow", "Left - Right"))
        self.rotate_group_box.setTitle(_translate("MainWindow", "Rotate Image"))
        self.rotate_left_button.setText(_translate("MainWindow", "Left 90"))
        self.rotate_right_button.setText(_translate("MainWindow", "Right 90"))
        self.pushButton.setText(_translate("MainWindow", "Face detector (May error)"))
        self.open_button.setText(_translate("MainWindow", "Open"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.prev_page_button.setText(_translate("MainWindow", "Prev"))
        self.next_page_button.setText(_translate("MainWindow", "Next"))
        self.undo_button.setText(_translate("MainWindow", "Undo"))
        self.original_image_button.setText(_translate("MainWindow", "Original"))
        self.menuAbout.setTitle(_translate("MainWindow", "Exit"))
        self.menuExit.setTitle(_translate("MainWindow", "Info"))
        self.actionAbout_us.setText(_translate("MainWindow", "About us"))
